### ISSUE TITLE
null pointer dereference

### ISSUE THREAD

**Issue by RobertLarsen** [Unitech/PM2#1119]
```
$ pm2 describe 0
Describing process with pid 0 - name CegoJabberServices
....
Revision control metadata

/media/data/software/node-v0.10.32/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:108
          if (typeof value_cell === 'object' && value_cell.length) {
                                                          ^
TypeError: Cannot read property 'length' of null
    at /media/data/software/node-v0.10.32/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:108:59
    at Array.forEach (native)
    at Table.toString (/media/data/software/node-v0.10.32/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:95:16)
    at Object.UX.describeTable (/media/data/software/node-v0.10.32/lib/node_modules/pm2/lib/CliUx.js:97:24)
    at /media/data/software/node-v0.10.32/lib/node_modules/pm2/lib/CLI.js:1225:12
    at Array.forEach (native)
    at /media/data/software/node-v0.10.32/lib/node_modules/pm2/lib/CLI.js:1224:18
    at /media/data/software/node-v0.10.32/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/media/data/software/node-v0.10.32/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:95:17)
```

**Comment by jshkurti** [comment]
Does it happen all the time or randomly ?
```npm i -g git://github.com/Unitech/PM2#development```
Should be fixed :)

**Comment by RobertLarsen** [comment]
It happens all the time.
I tried the development branch, but it still happens:
```
TypeError: Cannot read property 'length' of null
    at /opt/node-v0.12.0/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:108:59
    at Array.forEach (native)
    at Table.toString (/opt/node-v0.12.0/lib/node_modules/pm2/node_modules/cli-table/lib/index.js:95:16)
    at Object.UX.describeTable (/opt/node-v0.12.0/lib/node_modules/pm2/lib/CliUx.js:114:24)
    at /opt/node-v0.12.0/lib/node_modules/pm2/lib/CLI.js:1241:12
    at Array.forEach (native)
    at /opt/node-v0.12.0/lib/node_modules/pm2/lib/CLI.js:1240:18
    at /opt/node-v0.12.0/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/opt/node-v0.12.0/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:107:17)
```

**Comment by jshkurti** [comment]
I did change something.
```npm i -g git://github.com/Unitech/PM2#development``` and try again please :)

**Comment by RobertLarsen** [comment]
MUCH better. Thanks :-)

**Comment by jshkurti** [comment]
Glad I could help you, it will be on the next release ;)
