### ISSUE TITLE
Garbage collection failed - v0.12.11

### ISSUE THREAD

**Issue by rudijs** [Unitech/PM2#1194]
Hi,

Am seeing "Garbage collection failed" every 30s running pm2 inside a Docker container.

Any tips on how I can debug this? I'm poking around but not sure I can see why or how to fix.

```
root@1973ae3c171b:/srv/ride-share-market-api# sudo -i -u rsm-data NODE_ENV=$NODE_ENV pm2 start /srv/ride-share-market-api/pm2.json --no-daemon
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2015-04-19 13:11:02: [PM2][WORKER] Started with refreshing interval: 30000
2015-04-19 13:11:02: [[[[ PM2/God daemon launched ]]]]
2015-04-19 13:11:02: BUS system [READY] on port /home/rsm-data/.pm2/pub.sock
2015-04-19 13:11:02: RPC interface [READY] on port /home/rsm-data/.pm2/rpc.sock
2015-04-19 13:11:02: Starting execution sequence in -fork mode- for app name:api-server id:0
2015-04-19 13:11:02: App name:api-server id:0 online
2015-04-19 13:11:02: [PM2] Process launched
2015-04-19 13:11:02: ┌────────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name   │ id │ mode │ pid │ status │ restart │ uptime │ memory      │ watching │
├────────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ api-server │ 0  │ fork │ 31  │ online │ 0       │ 0s     │ 12.539 MB   │ disabled │
└────────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────────────┴──────────┘
2015-04-19 13:11:02:  Use `pm2 show <id|name>` to get more details about an app
2015-04-19 13:11:02: --no-daemon option enabled = do not exit pm2 CLI
2015-04-19 13:11:02: PM2 daemon PID = 22
2015-04-19 13:11:02: PM2: Log file "/home/rsm-data/.pm2/pm2.log" does not exist.
2015-04-19 13:11:32: Garbage collection failed
2015-04-19 13:12:02: Garbage collection failed
2015-04-19 13:12:32: Garbage collection failed
```

Here's my json config, I also had to set the full path the the log and pid directories, relative paths didn't work:

```
{
  "apps": [
    {
      "name": "api-server",
      "script": "server.js",
      "cwd": "/srv/ride-share-market-api",
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "error_file": "/srv/ride-share-market-api/log/pm2-api-server.stderr.log",
      "out_file": "/srv/ride-share-market-api/log/pm2-api-server.stdout.log",
      "pid_file": "/srv/ride-share-market-api/pids/pm2-api-server.pid"
    }
  ]
}
```

**Comment by rudijs** [comment]
Note .. I can use the --silent flag to stop the message output every 30s, but is this a bad idea?

**Comment by rudijs** [comment]
Inside the running Docker container I can run the node REPL:

Using iojs 1.5.1 global.gc is not enabled by default it seems:

```
 node
> typeof global
'object'
> typeof global.gc
'undefined'
```
Enable it:

```
node --expose-gc
> typeof global
'object'
> typeof global.gc
'function'
```

So I add "node_args": "--expose-gc" to my pm2 json config but still the "Garbage collection failed" every 30s.

Not sure what's up?

**Comment by jshkurti** [comment]
I just tried it with iojs-1.5.1 and it worked fine.
You don't have to add --expose-gc to your args since we do it when the daemon is launched :
https://github.com/Unitech/PM2/blob/master/lib/Satan.js#L331

This is strange.
Have you tried ```pm2 update``` ?

**Comment by simonguest** [comment]
I also see this. Running 0.12.11 of pm2 on node 0.12.2. Only happens when run inside the docker container, and messages appear every 30 sec.

**Comment by jshkurti** [comment]
Do you, by any chance run it in --no-daemon mode ?

**Comment by simonguest** [comment]
Yes, that's required to prevent the docker container from terminating.

**Comment by rudijs** [comment]
@jshkurti Yes also --no-daemon mode. Once the container is running using "docker logs" on the container will show the messages every 30s.

Are you guys working Docker and/or are familiar with it?

I could create a simple Dockerfile in this issue for help with debugging.

Thanks.

**Comment by simonguest** [comment]
Here is the repo/commit that I was trying to get pm2 to work with. Refer to the Dockerfile to see how the image is built.

https://github.com/simonguest/docker-node/tree/9c25f76afd191dc2be8e97fbdac9a8c250dcbfb6

**Comment by rudijs** [comment]
@simonguest That's a good looking Dockerfile to with on this issue.

**Comment by jshkurti** [comment]
That's normal then.
The `--expose-gc``` flag is set when we spawn the daemon here :
https://github.com/Unitech/PM2/blob/master/lib/Satan.js#L331-L354

But when you run in no-daemon mode, node is executed here :
https://github.com/Unitech/PM2/blob/master/bin/pm2#L1

I tried something like ```#!/usr/bin/env node --expose-gc``` but no luck :/
I can't seem to find out how to pass an arg to node with the shebang line..

**Comment by jorge-d** [comment]
As far as I can see from this [Stackoverflow question](http://stackoverflow.com/a/16549517/1991244) it looks like you can only pass in one argument to a shebang

**Comment by Unitech** [comment]
We can pass the expose-gc arguments withing the hashbang.
I dropped it some time ago but it was working well:
https://github.com/Unitech/PM2/commit/f2997a0fb2cab5e1d81d23455dbb3eae910c250b#diff-bb183d8324da61d7b5743e9f8a61da6e

**Comment by Unitech** [comment]
not sure that this hack is supported under windows

**Comment by rudijs** [comment]
@Unitech I'm using Linux/Docker with PM2 so I'll admit I'm not too concerned with Windows support.

Could we apply this option with a Linux/Unix only flag?

**Comment by shamasis** [comment]
Hello @Unitech. This particular bug in v0.12.11 and the log bug in v0.12.12 was preventing us from upgrading from v0.12.10. I was wondering if v0.12.13 fixes this bug.

I am facing this 30 second repeated garbage collection failure log.
- only when in docker
- only when `--no-daemon`
- only with node 0.12.2
- only in pm2 version 0.12.11

But, we cannot change node version or do anything else to stop it. Let us know of 0.12.13 fixes this. :-)

**Comment by soyuka** [comment]
Should be fixed https://github.com/Unitech/PM2/commit/59f19cd440412174a7a4e52d677cee0592b07e19

**Comment by Shawyeok** [comment]
@soyuka Actually, it is not fixed. I am reproduce this problem below:
```shell
[root@601897d9a1b9 src]# node -v
v5.11.1
[root@601897d9a1b9 src]# pm2 version
1.1.3
[root@601897d9a1b9 src]# ps -ef | grep pm2
root         1     0 23 May25 ?        05:37:57 node /usr/bin/pm2 start --no-daemon pm2-config.json
[root@601897d9a1b9 src]# uname -a
Linux 601897d9a1b9 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@601897d9a1b9 src]# #I am in a docker container, docker version is 1.9.1
```

**Comment by soyuka** [comment]
This is because gc is not available ([source](https://github.com/Unitech/pm2/blob/79ba743723131436bd049cc952e2b1f1158bc84c/lib/God/Methods.js#L317)). I think you need to add `--expose-gc` in your `node_args`.
