### ISSUE TITLE
Unable to (re)start errored process: Process <id> not found

### ISSUE THREAD

**Issue by raine** [Unitech/pm2#1983]
![screen shot 2016-02-29 at 12](https://cloud.githubusercontent.com/assets/11027/13391951/14479d74-dee0-11e5-9c3a-b074993847f1.png)

Seems like a bug to me.

**Comment by Unitech** [comment]
Weird, just tried here, everything is fine,
Can you try pm2 restart <app_name> ?

**Comment by raine** [comment]
Same thing.

**Comment by raine** [comment]
I still have the process in errored state if you want me to dig up something that would help in debugging.

**Comment by Unitech** [comment]
`pm2 restart 7` ?

**Comment by raine** [comment]
Same thing.

**Comment by Unitech** [comment]
`pm2 update`

**Comment by raine** [comment]
That made all processes restart and that particular process is also online now.

**Comment by Unitech** [comment]
and if you try again `pm2 restart` with an id or application name, does it work?

**Comment by raine** [comment]
I got into this state again, one of the processes got into errored state and I couldn't restart it. `pm2 update` fixed it but it requires manual work and monitoring so it's not really an acceptable solution I'm afraid.

**Comment by Unitech** [comment]
closing in favor of #2061

**Comment by JSkrip** [comment]
pm2 update - helped for me!) thank you!

**Comment by majimboo** [comment]
I'm experiencing this now. On a live server. Will doing pm2 update restart all services?

**Comment by AnujPancholi** [comment]
Got this error once - process stopped and just wouldn't start up again. Turns out that there were too many background processes running on the server that were hogging too much memory. Killed them, started my process up again, and it worked.

**Comment by akshay-squareboat** [comment]
> `pm2 update`

worked

**Comment by imjeffparedes** [comment]
Still having issue on v4. `pm2 update` is not an acceptable solution as it restarted all of our services.

**Comment by michel-el-hajj** [comment]
Still having the same issue in v4.5.4 and it's even worse. I found that my apps are running in the background and pm2 status shows the apps as stopped.
pm2 update removed this error but started to have address already in use so i had to kill the pid of the background process, then reloaded my apps and everything is back to normal.
i am upgrading to 5.1.0 hoping that this issue is fixed.

**Comment by JaivalBhup** [comment]
I am still having the same issue in v5.1.0. Restarting the service says process not found. Only pm2 update works and its not an reliable solution. 
Any help is appreciated.

**Comment by pujoljulia** [comment]
Same here - you really need to have a look into this. It's a very serious thing that process stops out of nowhere.

**Comment by Hertzogas** [comment]
I have a same issue 5.1.0

**Comment by JaivalBhup** [comment]
I solved the issue. 
The problem is environment variables. The pm2 variables might be overwritten or changed.

**Comment by JaivalBhup** [comment]
add to system variable  " %SystemRoot%/System32/Wbem"

This should solve the problem.

**Comment by n0099** [comment]
For me this happens after I've [changed the username](https://serverfault.com/questions/437342/how-can-i-rename-a-unix-user) that `pm2` is running
```bash
killall pm2
cd /home/newusername/.pm2
sed -i 's/oldusername/newusername/' dump.pm2
pm2 resurrect
pm2 update
pm2 ls
pm2 save
```

**Comment by thedevanand** [comment]
Is there any update on this? This issue is still happening. Somehow I got a hint that issue might be a bugged fs library so I upgraded node version to latest. And it did indeed work but it's not anymore. I've tried installing various pm2 versions as well but all of them have errors/deprecated libraries. This is happening on a windows server, never faced any issue on linux
