### ISSUE TITLE
get stuck on windows server 2003

### ISSUE THREAD

**Issue by farell** [Unitech/pm2#2298]
If reporting a bug, please use the following template.

#### Expected behaviour

Successfully start app as normal

#### Actual behaviour
```
![qq 20160725124506](https://cloud.githubusercontent.com/assets/2083201/17091002/be410d82-5268-11e6-87f7-e5414c2dbfc1.jpg)

as the above picture shows, after printing out "[PM2] Done",it stuck until I type "ctrl + c"
```
#### Steps to reproduce
```
1.install node.js 5.2.0
2.install pm2
3.start app using pm2
```
#### Software versions used

```
OS         :Microsoft Windows Server 2003 Enterprise Edition Service Pack 2
node.js    :5.2.0
PM2        :1.1.3
```

#### PM2 Log output

Use the command: `tail --lines 50 ~/.pm2/pm2.log`

cannot find file pm2.log

cf CONTRIBUTING.md for more informations

It works well on Windows 7 and Windows Server 2008

**Comment by Unitech** [comment]
```
$ npm install pm2@next -g
```

should fix the issue ;)

**Comment by farell** [comment]
I run "npm install pm2@next -g" successfully ,and try to start a app ,the bug remained,
here's the pm2.log content:

2016-08-01 10:38:57: ===============================================================================
2016-08-01 10:38:57: --- New PM2 Daemon started ----------------------------------------------------
2016-08-01 10:38:57: Time                 : Mon Aug 01 2016 10:38:57 GMT+0800 (中国标准时间)
2016-08-01 10:38:57: PM2 version          : 2.0.2
2016-08-01 10:38:57: Node.js version      : 5.2.0
2016-08-01 10:38:57: Current arch         : ia32
2016-08-01 10:38:57: PM2 home             : C:\Users\Administrator\.pm2
2016-08-01 10:38:57: PM2 PID file         : C:\Users\Administrator\.pm2\pm2.pid
2016-08-01 10:38:57: RPC socket file      : \\.\pipe\rpc.sock
2016-08-01 10:38:57: BUS socket file      : \\.\pipe\pub.sock
2016-08-01 10:38:57: Application log path : C:\Users\Administrator\.pm2\logs
2016-08-01 10:38:57: Process dump file    : C:\Users\Administrator\.pm2\dump.pm2
2016-08-01 10:38:57: Concurrent actions   : 4
2016-08-01 10:38:57: SIGTERM timeout      : 1600
2016-08-01 10:38:57: ===============================================================================
2016-08-01 10:39:21: Starting execution sequence in -fork mode- for app name:RedisServer id:0
2016-08-01 10:39:21: App name:RedisServer id:0 online
