### ISSUE TITLE
zero downtime reload doesn't work

### ISSUE THREAD

**Issue by tadjik1** [Unitech/pm2#2942]
**What's going wrong?**
When I'm reloading application connection between it and nginx drop, so users get error 502.

**How could we reproduce this issue?**
ecosystem.json:
```
{
  "apps": [
    {
      "name":               "application",
      "script":             "bin/server.js",
      "instances":          "2",
      "node_args":          "",
      "exec_mode":          "cluster_mode",
      "max_memory_restart": "2G",
      "kill_timeout":       5000,
      "wait_ready":         true,
      "log_file":           "/var/log/node/log_file.log",
      "error_file":         "/var/log/node/err.log",
      "out_file":           "/var/log/node/out.log",
      "cwd":                "/js/application",
      "env":                {
        "HOST":                        "127.0.0.1",
        "PORT":                        "3000",
        "PM2_GRACEFUL_LISTEN_TIMEOUT": 5000,
        "PM2_GRACEFUL_TIMEOUT":        5000,
        "ASSET_VERSIONING":            "file",
        "NODE_ENV":                    "production"
      }
    }
  ]
}
```

nginx configuration:
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Nginx-Geo $geoip_country_code;

proxy_set_header Host $http_host;

proxy_pass http://127.0.0.1:3000;
proxy_redirect off;
proxy_buffering off;
proxy_http_version 1.1;
proxy_read_timeout 3600;
proxy_send_timeout   90;
proxy_connect_timeout 5;
```

Also there is code inside application that fire both events: for shutdown and launch application.

Launch `siege`: `siege -b -c 2 http://localhost:3000` and try `pm2 reload all`. Most interesting part - this error occurs in ~10% of all reloads.

## Supporting information

```
PM2 version: `pm2 -v` - `2.4.6`
Node version: `node -v` - `7.10.0`
Windows? Mac? Linux? `Debian`
```

**Comment by vmarchaud** [comment]
Can you try with pm2 `2.5` ? we fixed an issue with the `wait-ready` mechanism maybe it come from that

**Comment by tadjik1** [comment]
@vmarchaud thanks for response.
I've updated pm2 to `2.5.0` but errors still occur.

One interesting detail that I noticed:
right now I'm reloading application using command below:
`pm2 startOrGracefulReload ecosystem.json`
but if I use `pm2 reload all` then I don't see any errors. So problem seems to be solved, can you please describe the difference between this 2 approaches? Because for me it look mostly the same.

**Comment by vmarchaud** [comment]
Indeed we still didn't documented it but you should only use `pm2 reload`, `pm2 gracefulReload` is pretty much deprecated

**Comment by tadjik1** [comment]
@vmarchaud oh, nice! thank you very much

**Comment by goetzc** [comment]
> Indeed, we still didn't documented it but you should only use pm2 reload, pm2 gracefulReload is pretty much deprecated

@vmarchaud any plan to document such things? Is this still the case?
