### ISSUE TITLE
bug: cpu display on pm2 3.0 is weird

### ISSUE THREAD

**Issue by Eywek** [Unitech/pm2#3708]
## What's going wrong?

```
┌─────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬───────────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu       │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼───────────┼────────────┼────────┼──────────┤
│ AXM-INTERACTION-APP │ 11 │ cluster │ 46589 │ online │ 0       │ 85m    │ 2.05%     │ 380.0 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 20 │ cluster │ 46835 │ online │ 0       │ 85m    │ 1.65625%  │ 361.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 19 │ cluster │ 46811 │ online │ 0       │ 85m    │ 2.21875%  │ 302.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 4  │ cluster │ 46389 │ online │ 0       │ 85m    │ 2.365625% │ 356.1 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 18 │ cluster │ 46791 │ online │ 0       │ 85m    │ 1.928125% │ 367.4 MB   │ ubuntu │ disabled │
```

CPU usage is not properly displayed. It should be around 40%-70%.

## Supporting information

```
===============================================================================
--- PM2 REPORT (Mon Jun 11 2018 17:45:05 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0-alpha1
node version         : 8.11.1
node path            : /usr/local/bin/pm2
argv                 : /usr/bin/node,/usr/local/share/.config/yarn/global/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
uptime               : 85min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0-alpha1
node version         : 8.11.1
node path            : /usr/local/bin/pm2
argv                 : /usr/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : ubuntu
uid                  : 1000
gid                  : 1000
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
cpus nb              : 32
freemem              : 121331007488
totalmem             : 135081730048
home                 : /home/ubuntu
===============================================================================
```

## Solution

Maybe this commit is guilty https://github.com/soyuka/pidusage/commit/88972d8cd38d4137b70261a830af22283b69c57c

**Comment by wallet77** [comment]
@soyuka any ideas ?

**Comment by soyuka** [comment]
Do the number stabilize over time? 

@simonepri this is what I was afraid of and was trying to explain :P.

From first sight it looks like the user is expecting `~40%` cpu usage, without taking cores into consideration in the calculus. With `32` cores, because we naively divide the result by the number of cores, cpu usage is indeed close to `1.25` per core. Still it's not as representative as the `40%` of total cpu.

I don't want to revert the PR because the maths are correct, but I wonder if we shouldn't give the total usage and the "per core" usage separately. Do you have an opinion?

**Comment by simonepri** [comment]
"we shouldn't give the total usage and the "per core" usage separately."
We do not know the "per core" usage actually.
We know how much CPU time the scheduler has given to the program.
This time could have been spent on any CPU.

So the point here is what kind of range we want to use by default.
- from **0** to **100** it makes sense most of the time
- from **0** to **100*vcore**

Ideally there isn't a lot difference between them, is just a constant multiplication factor.

**Comment by simonepri** [comment]
@soyuka we need to double check the mats for the `procfile` version.
I'm not sure if the math is correct for multi threaded processes.

**Comment by vmarchaud** [comment]
@soyuka In this case we are expecting much more (@Eywek work @keymetrics btw).
We have upgraded to the dev version of pm2 few of our production servers (which contained the last version of pidusage) and saw our numbers dropped from 80-100 to 0.5-1.5 which is, 100 times lower than the actual cpu usage (maybe someone missed a `* 100` somwhere ?)

**Comment by simonepri** [comment]
@vmarchaud if you multiply the percentages for the number of vcores you should get the old percentage back. Can you confirm this?

**Comment by soyuka** [comment]
Exactly what you said @simonepri ! 

@vmarchaud for now I'll just revert the patch that introduced this bug and we'll keep you up to date on how we can introduce support for cores computation in pidusage.

**Comment by simonepri** [comment]
@soyuka actually is not that easy.
the `ps`, `procfile` and `wmic` version should all behave coherently about the percentage range.
I think that now they all reports 0-100 readings but as I said I'm not 100% sure.

**Comment by vmarchaud** [comment]
thanks @soyuka for the revert, we will test this tomorrow.
However i dont see the point of getting the cpu usage for one app compared to the server, you want to know how much core your app using right ?

**Comment by soyuka** [comment]
Should be fixed in `2.0.8` (`npm update pm2` might be enough).

**Comment by Eywek** [comment]
It seems works on 1 server
```
┌─────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬───────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu   │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼───────┼────────────┼────────┼──────────┤
│ AXM-DIGESTERS       │ 13 │ cluster │ 11992 │ online │ 0       │ 5m     │ 28.4% │ 123.2 MB   │ ubuntu │ disabled │
│ AXM-DIGESTERS       │ 12 │ cluster │ 11964 │ online │ 0       │ 5m     │ 32.5% │ 117.4 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 9  │ cluster │ 11921 │ online │ 0       │ 5m     │ 25.6% │ 159.7 MB   │ ubuntu │ disabled │
```

But on another server, I can't do `pm2 ls`:
```
ubuntu@tau-web:~$ pm2 ls
ubuntu@tau-web:~$ echo $?
1
```
Only `sudo pm2 ls` works. But CPU values still broken:
```
┌─────────────────────┬────┬─────────┬────────┬────────┬─────────┬────────┬───────────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid    │ status │ restart │ uptime │ cpu       │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼────────┼────────┼─────────┼────────┼───────────┼────────────┼────────┼──────────┤
│ AXM-INTERACTION-APP │ 11 │ cluster │ 118154 │ online │ 0       │ 8m     │ 2.33125%  │ 277.9 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 20 │ cluster │ 118395 │ online │ 0       │ 8m     │ 1.896875% │ 236.9 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 19 │ cluster │ 118373 │ online │ 0       │ 8m     │ 1.7375%   │ 254.2 MB   │ ubuntu │ disabled │
```

`pm2 report` for broken server:
```
===============================================================================
--- PM2 REPORT (Tue Jun 12 2018 11:18:54 GMT+0200 (CEST)) ---------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.0.0-alpha1
node version         : 8.11.1
node path            : undefined
argv                 : /usr/bin/node,/usr/local/share/.config/yarn/global/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 9min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.0.0-alpha1
node version         : 8.11.1
node path            : undefined
argv                 : /usr/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
cpus nb              : 32
freemem              : 119064248320
totalmem             : 135081730048
home                 : /home/ubuntu
===============================================================================
--- PM2 list -----------------------------------------------
┌─────────────────────┬────┬─────────┬────────┬────────┬─────────┬────────┬───────────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid    │ status │ restart │ uptime │ cpu       │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼────────┼────────┼─────────┼────────┼───────────┼────────────┼────────┼──────────┤
│ AXM-INTERACTION-APP │ 11 │ cluster │ 118154 │ online │ 0       │ 9m     │ 2.35625%  │ 282.0 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 20 │ cluster │ 118395 │ online │ 0       │ 9m     │ 1.903125% │ 238.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 19 │ cluster │ 118373 │ online │ 0       │ 9m     │ 1.746875% │ 252.3 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 4  │ cluster │ 117944 │ online │ 0       │ 9m     │ 2.096875% │ 268.1 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 18 │ cluster │ 118329 │ online │ 0       │ 9m     │ 1.9375%   │ 260.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 6  │ cluster │ 117976 │ online │ 0       │ 9m     │ 2.125%    │ 263.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 7  │ cluster │ 118021 │ online │ 0       │ 9m     │ 2.859375% │ 245.2 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 8  │ cluster │ 118044 │ online │ 0       │ 9m     │ 1.965625% │ 264.1 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 9  │ cluster │ 118083 │ online │ 0       │ 9m     │ 2.346875% │ 298.6 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 10 │ cluster │ 118108 │ online │ 0       │ 9m     │ 1.934375% │ 249.7 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 17 │ cluster │ 118315 │ online │ 0       │ 9m     │ 1.884375% │ 257.2 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 1  │ cluster │ 117912 │ online │ 0       │ 9m     │ 2.396875% │ 247.2 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 16 │ cluster │ 118277 │ online │ 0       │ 9m     │ 2.446875% │ 225.2 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 14 │ cluster │ 118226 │ online │ 0       │ 9m     │ 2.009375% │ 262.4 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 15 │ cluster │ 118267 │ online │ 0       │ 9m     │ 3.6875%   │ 1.7 GB     │ ubuntu │ disabled │
│ AXM-LIMIT-WORKER    │ 5  │ fork    │ 117966 │ online │ 0       │ 9m     │ 1.621875% │ 136.0 MB   │ ubuntu │ disabled │
│ AXM-NOTIFICATION    │ 2  │ fork    │ 117928 │ online │ 0       │ 9m     │ 0.015625% │ 91.0 MB    │ ubuntu │ disabled │
│ AXM-PROXY           │ 13 │ cluster │ 118210 │ online │ 0       │ 9m     │ 0.090625% │ 104.9 MB   │ ubuntu │ disabled │
│ AXM-PROXY           │ 12 │ cluster │ 118165 │ online │ 0       │ 9m     │ 0.09375%  │ 103.9 MB   │ ubuntu │ disabled │
│ AXM-REALTIME        │ 3  │ fork    │ 117936 │ online │ 0       │ 9m     │ 0.384375% │ 164.7 MB   │ ubuntu │ disabled │
│ AXM-WEB-API ⏱       │ 0  │ fork    │ 117917 │ online │ 0       │ 9m     │ 0.31875%  │ 78.7 MB    │ ubuntu │ disabled │
└─────────────────────┴────┴─────────┴────────┴────────┴─────────┴────────┴───────────┴────────────┴────────┴──────────┘
 Module activated
┌──────────────────────┬─────────┬────────────┬────────┬─────────┬───────────┬──────────────┬──────┐
│ Module               │ version │ target PID │ status │ restart │ cpu       │ memory       │ user │
├──────────────────────┼─────────┼────────────┼────────┼─────────┼───────────┼──────────────┼──────┤
│ pm2-agent-monitoring │ 1.5.1   │ 118540     │ online │ 0       │ 0.046875% │ 66.156 MB    │ root │
│ pm2-probe            │ 1.5.5   │ 117902     │ online │ 0       │ 0.215625% │ 86.332 MB    │ root │
│ pm2-redis            │ 2.1.0   │ 10799      │ online │ 0       │ 1.903125% │ 125.324 MB   │ root │
│ pm2-server-monit     │ 2.6.2   │ N/A        │ online │ 0       │ 0.053125% │ 44.387 MB    │ root │
└──────────────────────┴─────────┴────────────┴────────┴─────────┴───────────┴──────────────┴──────┘
===============================================================================
--- Daemon logs --------------------------------------------
/home/ubuntu/.pm2/pm2.log last 20 lines:
PM2        | [2018-06-12 11:09:29] PM2 error: (node:117902) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -cluster mode- for app name:AXM-INTERACTION-APP id:18
PM2        | [2018-06-12 11:09:29] PM2 log: App name:AXM-INTERACTION-APP id:17 online
PM2        | [2018-06-12 11:09:29] PM2 error: (node:117902) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -cluster mode- for app name:AXM-INTERACTION-APP id:19
PM2        | [2018-06-12 11:09:29] PM2 log: App name:AXM-INTERACTION-APP id:18 online
PM2        | [2018-06-12 11:09:29] PM2 error: (node:117902) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -cluster mode- for app name:AXM-INTERACTION-APP id:20
PM2        | [2018-06-12 11:09:29] PM2 log: App name:AXM-INTERACTION-APP id:20 online
PM2        | [2018-06-12 11:09:29] PM2 error: (node:117902) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-12 11:09:29] PM2 log: App name:AXM-INTERACTION-APP id:19 online
PM2        | [2018-06-12 11:09:29] PM2 error: (node:117902) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -fork mode- for app name:pm2-server-monit id:21
PM2        | [2018-06-12 11:09:29] PM2 log: App name:pm2-server-monit id:21 online
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -fork mode- for app name:pm2-redis id:22
PM2        | [2018-06-12 11:09:29] PM2 log: App name:pm2-redis id:22 online
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -fork mode- for app name:pm2-agent-monitoring id:23
PM2        | [2018-06-12 11:09:29] PM2 log: App name:pm2-agent-monitoring id:23 online
PM2        | [2018-06-12 11:09:29] PM2 log: Starting execution sequence in -fork mode- for app name:pm2-probe id:24
PM2        | [2018-06-12 11:09:29] PM2 log: App name:pm2-probe id:24 online
```

**Comment by soyuka** [comment]
> Only sudo pm2 ls works. But CPU values still broken:

The npm update should be done with the correct user.

**Comment by Eywek** [comment]
Yep and it still broken

**Comment by soyuka** [comment]
> Yep and it still broken

Because pm2 is still using the old version of pidusage with your root user :). I can't really help you more on this.

**Comment by Eywek** [comment]
Fixed sorry

**Comment by vmarchaud** [comment]
@soyuka In the regards of what wee should show : 

> These values measure time spent in user and system code respectively, and may end up being greater than actual elapsed time if multiple CPU cores are performing work for this process.

I think the main problem here is indeed that the definition of cpu usage is different from people to people.
What i think it the main definition is : How much CPU my application is using ?

In the context of NodeJS (because every runtime has his own threading model), we can assume that only one thread do all the work (the one of the event loop) so one application should range between 0-100% (since one thread can't be actually shared between cores, it should max at one cpu used).
If we look at one of the most used monitoring tool in the world (htop/top), the cpu usage is clearly defined as . And changing this would be really hard for user to understand

In contrary, what (i think) you tried to achieve is to answer was : How much CPU resource of my server this application is using ?
In this case, giving the usage compared to the whole server is a correct metric, but the world didn't choose this as a definition of cpu usage (at least in my view).

**Comment by soyuka** [comment]
I completely agree on that! 

Let me know if there's another issue with pidusage since last patch ;). We'll keep the value between `0` and `100`! I'll add a new metric to get the proper value though.

**Comment by simonepri** [comment]
> In the context of NodeJS (because every runtime has his own threading model), we can assume that only one thread do all the work (the one of the event loop) so one application should range between 0-100% (since one thread can't be actually shared between cores, it should max at one cpu used).

FWIK each async i/o operation done by the code creates a new thread and then the result is processed by the event loop thread.
This means that for a NodeJS process it may happen that the cpu usage is greater than 100%.

**Comment by simonepri** [comment]
> We'll keep the value between 0 and 100! I'll add a new metric to get the proper value though.
Let's just say that we just show the cpu usage as ps/top and other does.

**Comment by soyuka** [comment]
Should be fixed.

**Comment by vmarchaud** [comment]
> FWIK each async i/o operation done by the code creates a new thread and then the result is processed by the event loop thread.
This means that for a NodeJS process it may happen that the cpu usage is greater than 100%.
Nope, the thread pool is only used for specific async operation (fs,dns), other API rely on `epoll` (specially the network), the thread pool is never used otherwise

**Comment by simonepri** [comment]
@vmarchaud thank you for the explanation!
@wallet77 The consumption should be per process, so I immagine that if the process has more than 1 thread the consumption will be cumulative of the work of all the threads.

**Comment by vmarchaud** [comment]
@wallet77 I agree with @simonepri that we need to show the cpu usage of all the threads that inherit from the main thread of the process, and thats the current behavior i think

**Comment by simonepri** [comment]
We can also obtain per thread readings, if possible we will try to integrate this functionality in the future.
See this example:
https://github.com/soyuka/pidusage/issues/57#issue-310089748

**Comment by Eywek** [comment]
So, now with pidusage@2.0.10, the CPU usage seems work like before, but with `pm2 ls` the display is weird:
```
┌─────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────────────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu                 │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────────────┼────────────┼────────┼──────────┤
│ AXM-DIGESTERS       │ 7  │ cluster │ 32248 │ online │ 0       │ 3D     │ 0%                  │ 130.6 MB   │ ubuntu │ disabled │
│ AXM-DIGESTERS       │ 8  │ cluster │ 32265 │ online │ 0       │ 3D     │ 0%                  │ 135.0 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 4  │ cluster │ 32206 │ online │ 0       │ 3D     │ 100.00000223517422% │ 257.9 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 1  │ cluster │ 32173 │ online │ 0       │ 3D     │ 0%                  │ 218.3 MB   │ ubuntu │ disabled │
│ AXM-LIMIT-WORKER    │ 6  │ fork    │ 32255 │ online │ 0       │ 3D     │ 0%                  │ 114.3 MB   │ ubuntu │ disabled │
│ AXM-NOTIFICATION    │ 2  │ fork    │ 32189 │ online │ 0       │ 3D     │ 0%                  │ 123.7 MB   │ ubuntu │ disabled │
│ AXM-PROXY           │ 5  │ cluster │ 5992  │ online │ 1       │ 3D     │ 0%                  │ 115.0 MB   │ ubuntu │ disabled │
│ AXM-REALTIME        │ 3  │ fork    │ 32198 │ online │ 0       │ 3D     │ 0%                  │ 119.8 MB   │ ubuntu │ disabled │
│ AXM-WEB-API         │ 0  │ fork    │ 32178 │ online │ 0       │ 3D     │ 0%                  │ 135.8 MB   │ ubuntu │ disabled │
└─────────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────────────┴────────────┴────────┴──────────┘
 Module activated
┌──────────────────────┬─────────┬────────────┬────────┬─────────┬─────────────────────┬─────────────┬────────┐
│ Module               │ version │ target PID │ status │ restart │ cpu                 │ memory      │ user   │
├──────────────────────┼─────────┼────────────┼────────┼─────────┼─────────────────────┼─────────────┼────────┤
│ pm2-agent-monitoring │ 1.5.1   │ 32514      │ online │ 1       │ 0%                  │ 57.258 MB   │ ubuntu │
│ pm2-elasticsearch    │ 1.0.0   │ N/A        │ online │ 0       │ 0%                  │ 0 B         │ ubuntu │
│ pm2-probe            │ 1.5.5   │ 32161      │ online │ 0       │ 100.00000223517422% │ 90.008 MB   │ ubuntu │
│ pm2-redis            │ 2.1.0   │ 15167      │ online │ 0       │ 100.00000223517422% │ 67.953 MB   │ ubuntu │
│ pm2-server-monit     │ 2.6.2   │ N/A        │ online │ 0       │ 0%                  │ 61.008 MB   │ ubuntu │
└──────────────────────┴─────────┴────────────┴────────┴─────────┴─────────────────────┴─────────────┴────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

But `pm2 report` display the right cpu usage:

```
--- PM2 list -----------------------------------------------
┌─────────────────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────────────┬────────────┬────────┬──────────┐
│ App name            │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu                 │ mem        │ user   │ watching │
├─────────────────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────────────┼────────────┼────────┼──────────┤
│ AXM-DIGESTERS       │ 7  │ cluster │ 32248 │ online │ 0       │ 3D     │ 33.870967735830035% │ 130.7 MB   │ ubuntu │ disabled │
│ AXM-DIGESTERS       │ 8  │ cluster │ 32265 │ online │ 0       │ 3D     │ 25.806451608251457% │ 138.0 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 4  │ cluster │ 32206 │ online │ 0       │ 3D     │ 19.354838706188595% │ 259.5 MB   │ ubuntu │ disabled │
│ AXM-INTERACTION-APP │ 1  │ cluster │ 32173 │ online │ 0       │ 3D     │ 38.70967741237719%  │ 217.8 MB   │ ubuntu │ disabled │
│ AXM-LIMIT-WORKER    │ 6  │ fork    │ 32255 │ online │ 0       │ 3D     │ 0%                  │ 112.3 MB   │ ubuntu │ disabled │
│ AXM-NOTIFICATION    │ 2  │ fork    │ 32189 │ online │ 0       │ 3D     │ 0%                  │ 124.2 MB   │ ubuntu │ disabled │
│ AXM-PROXY           │ 5  │ cluster │ 5992  │ online │ 1       │ 3D     │ 1.612903225515716%  │ 115.0 MB   │ ubuntu │ disabled │
│ AXM-REALTIME        │ 3  │ fork    │ 32198 │ online │ 0       │ 3D     │ 4.838709676547149%  │ 115.9 MB   │ ubuntu │ disabled │
│ AXM-WEB-API         │ 0  │ fork    │ 32178 │ online │ 0       │ 3D     │ 0%                  │ 139.8 MB   │ ubuntu │ disabled │
└─────────────────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────────────┴────────────┴────────┴──────────┘
 Module activated
┌──────────────────────┬─────────┬────────────┬────────┬─────────┬────────────────────┬─────────────┬────────┐
│ Module               │ version │ target PID │ status │ restart │ cpu                │ memory      │ user   │
├──────────────────────┼─────────┼────────────┼────────┼─────────┼────────────────────┼─────────────┼────────┤
│ pm2-agent-monitoring │ 1.5.1   │ 32514      │ online │ 1       │ 0%                 │ 55.008 MB   │ ubuntu │
│ pm2-elasticsearch    │ 1.0.0   │ N/A        │ online │ 0       │ 0%                 │ 0 B         │ ubuntu │
│ pm2-probe            │ 1.5.5   │ 32161      │ online │ 0       │ 1.612903225515716% │ 88.746 MB   │ ubuntu │
│ pm2-redis            │ 2.1.0   │ 15167      │ online │ 0       │ 22.58064515722003% │ 67.207 MB   │ ubuntu │
│ pm2-server-monit     │ 2.6.2   │ N/A        │ online │ 0       │ 1.612903225515716% │ 61.098 MB   │ ubuntu │
└──────────────────────┴─────────┴────────────┴────────┴─────────┴────────────────────┴─────────────┴────────┘
===============================================================================
```

And `pm2-io-agent` get the right value too.

**Comment by soyuka** [comment]
As I said on slack, for `pm2 list` it'd be better to use `ctime / elapsed` to have a "global cpu usage" metric.

**Comment by wallet77** [comment]
Hi there,
@soyuka  we will release pm2 thursday (21/06).
So we need to fix this or to rollback.

**Comment by Eywek** [comment]
So, it works with #3725, but CPU is not rounded for modules:

```
 Module activated
┌──────────────────────┬─────────┬────────────┬────────┬─────────┬────────────────────┬──────────────┬────────┐
│ Module               │ version │ target PID │ status │ restart │ cpu                │ memory       │ user   │
├──────────────────────┼─────────┼────────────┼────────┼─────────┼────────────────────┼──────────────┼────────┤
│ pm2-agent-monitoring │ 1.5.1   │ 118381     │ online │ 0       │ 2.564102566306878% │ 64.191 MB    │ ubuntu │
│ pm2-probe            │ 1.5.5   │ 117741     │ online │ 0       │ 5.128205132613756% │ 80.980 MB    │ ubuntu │
│ pm2-redis            │ 2.1.0   │ 10799      │ online │ 0       │ 48.71794875983068% │ 130.645 MB   │ ubuntu │
│ pm2-server-monit     │ 2.6.2   │ N/A        │ online │ 0       │ 0%                 │ 33.180 MB    │ ubuntu │
└──────────────────────┴─────────┴────────────┴────────┴─────────┴────────────────────┴──────────────┴────────┘
```

**Comment by soyuka** [comment]
I've patched CliUx but may have forgot modules UI! Where is it located in the code @wallet77 ?

https://github.com/Unitech/pm2/pull/3725/files#diff-36617d5cf74241f64b44c1968da9a024R330

**Comment by wallet77** [comment]
I'd have said here : https://github.com/Unitech/pm2/blob/b3ff38c4fbf90746a77890c67c916fe5317ffd39/lib/API/CliUx.js#L296

**Comment by wallet77** [comment]
PM2 3.0.0 has been released:

$ npm install pm2@latest -g
$ pm2 update

Be aware of breaking changes, especially drop support for node 0.12.
Full list here : https://github.com/Unitech/pm2/blob/master/CHANGELOG.md
