### ISSUE TITLE
pm2 Memory Leak

### ISSUE THREAD

**Issue by adamjeffery-dev** [Unitech/pm2#3712]
## What's going wrong?

pm2 slowly (over the course of an hour uses LOTS of RAM)!! And often runs at near 100% of CPU.

## How could we reproduce this issue?

Use pm2 2.10.4 to run a node Process and wait.

## Supporting information

npm 5.6.0
pm2 2.10.4
Centos v6.9
Node v8.9.4

```
==========================================================================
--- PM2 REPORT (Wed Jun 13 2018 09:15:24 GMT+0100 (BST)) ----------------------
==========================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.10.4
node version         : 8.9.4
node path            : /usr/bin/pm2
argv                 : /root/.nvm/versions/node/v8.9.4/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 70min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.10.4
node version         : 8.9.4
node path            : /usr/bin/pm2
argv                 : /root/.nvm/versions/node/v8.9.4/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : AMD Opteron(tm) Processor 6380
cpus nb              : 8
freemem              : 4429713408
totalmem             : 16717795328
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌────────────────────────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name                   │ id │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem        │ user │ watching │
├────────────────────────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ asterisk-gateway-ALL       │ 0  │ fork │ 45165 │ online  │ 1       │ 68m    │ 54% │ 96.4 MB    │ root │ disabled │
│ realtime-event-manager-ALL │ 1  │ fork │ 44742 │ online  │ 0       │ 69m    │ 99% │ 267.9 MB   │ root │ disabled │
│ tt-gateway-1               │ 2  │ fork │ 46125 │ online  │ 0       │ 46m    │ 55% │ 157.1 MB   │ root │ disabled │
│ tt-gateway-10              │ 11 │ fork │ 45055 │ online  │ 0       │ 69m    │ 37% │ 90.1 MB    │ root │ disabled │
│ tt-gateway-2               │ 3  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-3               │ 4  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-4               │ 5  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-5               │ 6  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-6               │ 7  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-7               │ 8  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-8               │ 9  │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
│ tt-gateway-9               │ 10 │ fork │ 0     │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
└────────────────────────────┴────┴──────┴───────┴─────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | [2018-06-13 08:29:47] PM2 log: Stopping app:tt-gateway-5 id:6
PM2        | [2018-06-13 08:29:48] PM2 log: pid=44890 msg=failed to kill - retrying in 100ms
PM2        | [2018-06-13 08:29:48] PM2 log: App [tt-gateway-5] with id [6] and pid [44890], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-13 08:29:48] PM2 log: pid=44890 msg=process killed
PM2        | [2018-06-13 08:29:51] PM2 log: Stopping app:tt-gateway-6 id:7
PM2        | [2018-06-13 08:29:52] PM2 log: pid=44933 msg=failed to kill - retrying in 100ms
PM2        | [2018-06-13 08:29:52] PM2 log: App [tt-gateway-6] with id [7] and pid [44933], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-13 08:29:52] PM2 log: pid=44933 msg=process killed
PM2        | [2018-06-13 08:29:55] PM2 log: Stopping app:tt-gateway-7 id:8
PM2        | [2018-06-13 08:29:56] PM2 log: pid=44966 msg=failed to kill - retrying in 100ms
PM2        | [2018-06-13 08:29:56] PM2 log: App [tt-gateway-7] with id [8] and pid [44966], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-13 08:29:56] PM2 log: pid=44966 msg=process killed
PM2        | [2018-06-13 08:29:58] PM2 log: Stopping app:tt-gateway-8 id:9
PM2        | [2018-06-13 08:29:59] PM2 log: pid=45004 msg=failed to kill - retrying in 100ms
PM2        | [2018-06-13 08:29:59] PM2 log: App [tt-gateway-8] with id [9] and pid [45004], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-13 08:29:59] PM2 log: pid=45004 msg=process killed
PM2        | [2018-06-13 08:30:02] PM2 log: Stopping app:tt-gateway-9 id:10
PM2        | [2018-06-13 08:30:03] PM2 log: pid=45021 msg=failed to kill - retrying in 100ms
PM2        | [2018-06-13 08:30:03] PM2 log: App [tt-gateway-9] with id [10] and pid [45021], exited with code [0] via signal [SIGINT]
PM2        | [2018-06-13 08:30:03] PM2 log: pid=45021 msg=process killed

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues

**Comment by mmpyro** [comment]
I have observer the same error for version 3.x and 2.9.x. pm2 start a lot of pm2 list process. Each of them uses about 0.7 % of total memory. When I tried to kill them using ps aux|grep -i pm2|awk '{print $2}'| xargs kill -9 but npm start it over and over again. If anyone knows workaround please shere with me.

**Comment by gotoin** [comment]
me too

**Comment by Unitech** [comment]
We inspect pm2 under heavy load before every release and we have not noticed any leak.

To report a potencial leak:
```
$ pm2 install pm2-probe
```

When PM2 is "leaking memory" please send a screenshot of htop filtered on PM2 + the pm2 ls command

**Comment by diegofontana** [comment]
me too @ 3.0.2
![bug-pm2](https://user-images.githubusercontent.com/13320581/43267713-19dbd19e-90c5-11e8-9b2b-c41332eef29e.jpg)

**Comment by Unitech** [comment]
It has been fixed, just kill all agent before updating `pkill -f Agent`.
Checked again in some production server, the previous agent was trying to resurrect PM2.

**Comment by swoofer** [comment]
i have same problem, 
my step: 
i kill instance "pm2"
-`npm install pm2@latest -g`
-`pm2 update`

After 15 min i have multi instance `node ` and ` pm2 agent` with only one app

**Comment by Unitech** [comment]
Again:

```bash
pkill -f Agent
npm install pm2@latest -g
pm2 update
```

**Comment by Unitech** [comment]
Can you run:

pm2 kill

Then check if there are Agent still running?

**Comment by Unitech** [comment]
Also @swoofer could you please display the content of the logfile ~/.pm2/agent.log thanks

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/issues/3834

**Comment by Unitech** [comment]
Fixed & Published, just update:

```bash
npm install pm2@latest -g
pm2 update
```

**Comment by diegofontana** [comment]
I have just updated and the problem persists....
As you can see in the "~/.pm2/agent.log", something makes the agent to crash and "re-initiate" over and over again..... i had to run "pkill -f Agent" to avoid the server crash, but whitout the agents no data is sent to pm2.io website 👎 , but its better no data then the a server crash....

```
===============================================================================
--- PM2 REPORT (Tue Aug 14 2018 22:59:15 GMT+0000 (Coordinated Universal Time))
===============================================================================
--- Daemon --------------------------------------------------------------------
pm2d version         : 3.0.3
node version         : 10.8.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 69min
===============================================================================
--- CLI -----------------------------------------------------------------------
local pm2            : 3.0.3
node version         : 10.8.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info ---------------------------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
cpus nb              : 2
freemem              : 1918013440
totalmem             : 4142145536
```

```
2018-08-14T22:38:51.986Z interactor:daemon Launching Interactor RPC server (bind to /home/ubuntu/.pm2/interactor.sock)
2018-08-14T22:38:53.109Z interactor:daemon Send to process daemon is started
2018-08-14T22:38:53.112Z interactor:reverse Reverse interactor is listening
2018-08-14T22:38:53.112Z interactor:daemon Interactor daemon started
-- FATAL EXCEPTION happened --
2018-08-14T22:38:53.113Z
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:628:16)
    at verifyEndpointCallback (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorDaemon.js:338:17)
    at async.each (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/TransporterInterface.js:79:7)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:992:24)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1064:13)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
Re-initiating Agent
[PM2 Agent] Using (Public key: 1rvp3hqt572s982) (Private key: yprba8985ylw3bb) (Info node: https://root.keymetrics.io)
2018-08-14T22:38:53.123Z interactor:pm2:interface PM2Interface instantiate
2018-08-14T22:38:53.259Z interactor:daemon Succesfully launched new agent
2018-08-14T22:38:53.259Z interactor:daemon Exiting Interactor
2018-08-14T22:38:53.260Z interactor:reverse Reverse interactor is no longer listening
```
