### ISSUE TITLE
Error : yarn add pm2 not working anymore

### ISSUE THREAD

**Issue by Miniplop** [Unitech/pm2#3770]
## What's going wrong?

When installing pm2 from yarn :

![image](https://user-images.githubusercontent.com/15800180/42331363-87d8c0ae-8075-11e8-894d-5cb1adb8b2ee.png)

seems to be an error with the certificate

## How could we reproduce this issue?

yarn version : 1.3.2
node : 8.4.0

launch yarn add pm2

## Supporting information

Impossible to run pm2 support

**Comment by wallet77** [comment]
Hi @Miniplop 

I've just tried and it works with the same version of node.
But with yarn 1.7.0

**Comment by TheAppleFreak** [comment]
For what it's worth, I'm unable to access [the PM2 website](https://pm2.io) myself, which is where that package is currently hosted. It just says for me that the domain was parked by the owner.

**Comment by tjinaton** [comment]
`npm install pm2 `

> fetch failed https://tgz.pm2.io/gkt-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND tgz.pm2.io tgz.pm2.io:443

not working also. 

> Whois result for pm2.io
Domain Name: pm2.io
Registry Domain ID: UNDEF-ROID
Registrar WHOIS Server: whois.gandi.net
Registrar URL: http://www.gandi.net
Updated Date: 2018-07-05T15:15:31Z
Creation Date: 2013-10-25T14:35:22Z

Domain is updated **today**

**Comment by tjinaton** [comment]
@wallet77 Note DNS-entries may be cached, so it is possible that you may experience problems later

**Comment by jmonster** [comment]
@tjinaton  Could you post the `ip` address so we may manually set it in our `/etc/hosts` file as a temp work around?

**Comment by wallet77** [comment]
> @wallet77 Note DNS-entries may be cached, so it is possible that you may experience problems later

Indeed. From my home it's seems npm works (probably because of cache), same if I access the tgz via https.
But with a fresh install of yarn it's fails.

Unfortunately I don't have access to DNS but problem is reported and will be fixed asap.

**Comment by Ancient123** [comment]
Flush dns. Their dns entry appears to be fixed now.

**Comment by wallet77** [comment]
Fixed !

Could you confirm @all ?

**Comment by jmonster** [comment]
```
sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache
```

Still not working for me; if someone could share the IP that would be great.. 

```
dig +short tgz.pm2.io
```

**Comment by Unitech** [comment]
Fixed sorry for that issue. Registrar UX interface are sometime misleading..
DNS correction being propagated right now

If you still have the issue:

```bash
$ npm install pm2 -g --no-optional
```

**Comment by serkanh** [comment]
I was able to flush my dns cache locally but circleci (using aws nameservers) ns servers are still not updated as of now. ```circleci@default-1752711d-74cf-4e17-b11a-f57b0e204ae9:~/project$ dig tgz.pm2.io @8.8.8.8

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> tgz.pm2.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21782
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tgz.pm2.io.                    IN      A

;; ANSWER SECTION:
tgz.pm2.io.             3599    IN      A       163.172.101.189

;; Query time: 174 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jul 05 18:04:55 UTC 2018
;; MSG SIZE  rcvd: 55

circleci@default-1752711d-74cf-4e17-b11a-f57b0e204ae9:~/project$ ```

**Comment by rhernand3z** [comment]
I am having the same issue when running `yarn add pm2`.
Attempting to run `yarn add pm2@x.x.x --exact` seemed to work for me, hope it helps.

**Comment by tjinaton** [comment]
A bit late but : Fixed: Thanx a lot...
