### ISSUE TITLE
support "type": "module" (esm for node 13)

### ISSUE THREAD

**Issue by siric** [Unitech/pm2#4540]
esm is no longer experimental in node 13, however pm2 does not read out `"type": "module"` from `package.json`, which means that esm imports/exports can not be used with pm2:

```
import { foo } from './foo.js';
       ^

SyntaxError: Unexpected token {
```

**Comment by r3gisc** [comment]
_Some investigations:_

- With "type":"module" in package.json

```
7|xxxx  | (node:24598) Warning: require() of ES modules is not supported.
7|xxxx  | require() of xxxx.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
7|xxxx  | Instead rename loader-scanner.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from xxxxx/package.json.
7|xxxx  | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxxx.js
7|xxxx  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
```

- With .mjs extension

```
9|xxxx  | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxxxx.mjs
9|xxxx  |     at Module.load (internal/modules/cjs/loader.js:981:11)
9|xxxx  |     at Function.Module._load (internal/modules/cjs/loader.js:891:14)
```

- Without neither .mjs or "type":"module"  :

```
8|xxxx  | (node:24843) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
8|xxxx  | xxxxx.js:10
8|xxxx  | import { Run } from 'xxxxxxx';
8|xxxx  | ^^^^^^
8|xxxx  | SyntaxError: Cannot use import statement outside a module
8|xxxx  |     at wrapSafe (internal/modules/cjs/loader.js:1050:16)
8|xxxx  |     at Module._compile (internal/modules/cjs/loader.js:1098:27)
8|xxxx  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
```

**The only workaround I've found so far is to keep esm is to use ESM loader with interpreterArgs: ['-r', 'esm'] params.
But it's really slow compared to native node 13 loader**

**Comment by bradocchs** [comment]
Same here. I'm using .mjs and node 13, but esm workaround not even working for me. App runs fine using systemd daemon.

**Comment by NeonCreativeStudios** [comment]
This is my first time using pm2 and I thought I was going insane! Have been googling about this for hours. I hope there will be a fix soon

**Comment by r3gisc** [comment]
**A quick and dirty fix for pm2/lib/ProcessContainerFork.js  :**
```
26 if (process.env.pm_exec_path)
     
27 // require('module')._load(process.env.pm_exec_path, null, true);   //REPLACE
    
27 import(process.env.pm_exec_path); // (we don't use await here)      //BY
```

**Workaround:**
I'm using a 'custom loader' which is faster than esm-loader and use Node 13 native one. 
Its goal is to bypass ProcessContainerFork.js


We need to use node interpreter args:
_(here as api, but can be done using command line/ecosystem file)_

```
pm2Options.interpreterArgs = '-- path/to/loader.js index.mjs' 

// "--" is mandatory because we don't want node to parse the our custom args
// our args will be placed before pm2's (ProcessContainerFork.js)
// with index.mjs as the ES6 target script
// need "type":"module" in package.json if mjs extension is not used
```

- loader.js

```
const moduleFile = process.cwd() + '/' + process.argv[2]
process.argv.splice(2, 2)
import (moduleFile)
```

**Comment by Unitech** [comment]
Thanks for this report and suggestion, will dig this

**Comment by DominusVilicus** [comment]
Is this seriously not working?

**Comment by DominusVilicus** [comment]
@Unitech how can I help? This is pretty critical for my team as we're using modules in production.

It's been enabled officially by node, although still experimental (it works great on my end)

**Comment by DominusVilicus** [comment]
@Unitech Plz comment, this has been out for some time now and it has not been addressed

**Comment by Unitech** [comment]
Will work on it by the next 7 days

**Comment by DominusVilicus** [comment]
Thanks, I've had to resort to using `forever`, but keen to switch back to pm2 once it's ready

**Comment by Unitech** [comment]
Ok I landed the ES module support

**Comment by Unitech** [comment]
Can anyone try it out please?

```
npm install Unitech/pm2#development -g
pm2 update
pm2 start app.mjs
```

Thank you!

**Comment by vitalets** [comment]
I've checked:
- `pm2 start app.mjs` - ok (package.type missing)  
- `pm2 start app.js` - ok (package.type = 'module')
- `pm2 start src/app.mjs` - ok (package.type missing)  
- `pm2 start src/app.js` - ERR_REQUIRE_ESM (package.type = 'module')

**Comment by Unitech** [comment]
Release on pm2 4.2.2

```
npm install pm2@latest -g
pm2 update
```

**Comment by r3gisc** [comment]
It works ! thanks a lot

**Comment by r3gisc** [comment]
Just a detail: according to Node.js doc: https://nodejs.org/api/esm.html

> The nearest parent package.json is defined as the first package.json found when searching in the current folder, that folder’s parent, **and so on up until the root of the volume is reached.**

Here  pm2 is checking by package.json  in the current folder and it's first parent.
In my case js is transpiled from src to a/deeper/folder then, i have to copy project root's package.json to deployment folder, but it's not a big deal.

**Comment by vitaliytv** [comment]
with ESM on windows my success only with:

`pm2 start node -- src/index.js`

**Comment by chrisstone07** [comment]
@r3gisc With node **12.18** and pm2 **4.4.0** pm2 all combinations that you mentioned fails with **ERR_REQUIRE_ESM** error, which version of node did you use to verify that it's working?

**Comment by iot-resister** [comment]
This does not work with the docker `pm2-runtime`. 

```Dockerfile
RUN yarn global add pm2@4.2.2
COPY . .
EXPOSE 8080
CMD [ "pm2-runtime", "index.js" ]
```
Gives:
````bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/app/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1154:13)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```
adding  `pm2 update`  doesn't fix either.

**Comment by DominusVilicus** [comment]
Having issues with this again

**Comment by pmikolajek** [comment]
@Unitech I'm getting `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module` on pm2 **4.4.0** with node **12.18.2**.

**Comment by alanyong91** [comment]
I don't understand why need to switch to `.mjs` extension.
I don't understand why after I add `"type": "module"` it still not working. 
I don't understand why need `esm` at the first place.
I don't understand after install `esm`, alias in `.babelrc` totally not working.

`pm2` doesn't seems fix the problem but create more problem.

**Comment by alanyong91** [comment]
Can we reopen this issue. pm2 4.4.0 have the same problem again

**Comment by zimtsui** [comment]
why folks above said it works with v4.2.2. ?
I have v4.4.2 installed but it still doesn't work

**Comment by Unitech** [comment]
This test: https://github.com/Unitech/pm2/blob/0d44c41b07193bb793420ea23c476e020f8e99d5/test/e2e/esmodule.sh is passing

What is wrong with these tests? Let me know so I can fix whatever is missing

**Comment by dthree** [comment]
@Unitech I figured out what is wrong.

In `pm2/lib/ProcessUtils.js`:

```
    try {
      data = JSON.parse(fs.readFileSync(path.join(path.dirname(exec_path), 'package.json')))
      if (data.type === 'module')
        return true
      else
        return false
    } catch(e) {
    }
```

In my use case, `index.js` is in a subdirectory, such as `app/lib/index.js`. The issue is that `path.join(path.dirname(exec_path)` looks for `package.json` in the same directory as `index.js`, silently fails, and then can't find it.

Can you modify this to look for `package.json` at the root of the directory?

**Comment by dthree** [comment]
[Something like this](https://github.com/sindresorhus/pkg-dir) would do the trick.7

**Comment by FbN** [comment]
I think the problem is that ESModules support is disabled for version below 13 (current LTS is 12.18.4) [See here](https://github.com/Unitech/pm2/compare/master...FbN:patch-1)

**Comment by zimtsui** [comment]
@Unitech if pm2 calls the user scripts with `require('userscript.js')` in an wrapper rather than with `process.fork('userscript.js')` directly, this issue technically cannot be fixed, because node v13+ forbids `require()` on commonjs, which has nothing to do with whether the function `require` is hooked by `-r esm`.

it's needed to make a big change about how pm2 calls user scripts. it should be:
- calling user scripts with `process.fork` directly
- or calling user scripts with `import()` in a wrapper

**Comment by devYusuf** [comment]
@Unitech it's still not working with "type": "module" in the package.json file, like in the picture below

![Screenshot from 2021-01-01 04-22-47](https://user-images.githubusercontent.com/48928718/103432966-0ba8b100-4be9-11eb-9f03-8787265070dc.png)

**Comment by BlueskyFR** [comment]
I can confirm that the `"type": "module"` in package.json does not work properly on NodeJS LTS

**Comment by dthree** [comment]
I don't know why this isn't getting any priority, I literally can't use PM2 with ESM modules.

**Comment by alanyong91** [comment]
use `babel` to build file and run with `pm2`

**Comment by nickpharrison** [comment]
Best workaround I've found for this is to change the name of the entry script from ending in ".js" to ending in ".mjs", not exactly an ideal solution, but it gets the job done as a temporary fix until this actually gets some attention

**Comment by Genshii8** [comment]
Using an Ecosystem file still doesn't work with ESM. pm2 needs to use `import` syntax or it could simply try to look for an Ecosystem file ending in `.cjs`.

For anyone having this issue, a really simple "workaround" is to just write your config file in YAML (see [here](https://pm2.keymetrics.io/docs/usage/application-declaration/)). i.e. `ecosystem.config.yaml` and point your scripts to it.

**Comment by alvinometric** [comment]
Same feeling as @dhtree, pm2 is blocking our migration to ESM. It's frustrating.

**Comment by Unitech** [comment]
With pm2#development:

app.js
```javascript
// app.mjs
import { addTwo } from './addTwo.js';

// Prints: 6
console.log(addTwo(4));
```

addTwo.js
```javascript
// addTwo.mjs
function addTwo(num) {
  return num + 2;
}

export { addTwo };
```

package.json:
```
{
  "name": "esm",
  "version": "1.0.0",
  "description": "",
  "main": "addTwo.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

```bash
❯ node -v
v15.12.0
```

Then when I start:
```bash
pm2 start app.js
```

It works:
```
4|app    | 6
PM2      | App [app:4] exited with code [0] via signal [SIGINT]
PM2      | App [app:4] starting in -fork mode-
PM2      | App [app:4] online
4|app    | 6
PM2      | App [app:4] exited with code [0] via signal [SIGINT]
PM2      | App [app:4] starting in -fork mode-
PM2      | App [app:4] online
4|app    | 6
PM2      | App [app:4] exited with code [0] via signal [SIGINT]
PM2      | App [app:4] starting in -fork mode-
PM2      | App [app:4] online
4|app    | 6
PM2      | App [app:4] exited with code [0] via signal [SIGINT]
PM2      | App [app:4] starting in -fork mode-
PM2      | App [app:4] online
4|app    | 6
``` 
```

**Comment by alvinometric** [comment]
This is fantastic!

**Comment by HRK44** [comment]
It works if the app.js file is at the root of the project, if it's deeper, doesn't work

**Comment by Unitech** [comment]
Tried to start a script in children folder and it still works:

![image](https://user-images.githubusercontent.com/757747/121012475-08b57c00-c798-11eb-9002-24e709e1c8ea.png)

**Comment by nickpharrison** [comment]
For anyone that wants another workaround, I have found that creating a separate entry script for the ecosystem file with extension `.mjs` works well, which then just imports the "real" entry script. ie having a file called `entry.mjs` which just contains:

```
import * as entry from './app.js';
```

**Comment by HRK44** [comment]
> Tried to start a script in children folder and it still works:
> 
> ![image](https://user-images.githubusercontent.com/757747/121012475-08b57c00-c798-11eb-9002-24e709e1c8ea.png)

Try one level deeper... esm/deep/app.js
I just tried and 1 level deep seems to work, 2 levels deep doesn't work :

- app.js root > works
- modules/app.js > works
- modules/api/app.js > not working

**Comment by Dhruv-Garg79** [comment]
node version : 14.16.0
start script in package.json - "cross-env NODE_ENV=development nodemon --es-module-specifier-resolution=node --experimental-modules --no-warnings src/common/bin/app.js"

getting below error on running `pm2 start npm -- run start`

```
0|npm      | Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Programs/npm' is not supported resolving ES modules imported from /home/dhruv/.nvm/versions/node/v14.16.0/lib/node_modules/pm2/lib/ProcessContainerFork.js
0|npm      |     at finalizeResolution (internal/modules/esm/resolve.js:272:17)
0|npm      |     at moduleResolve (internal/modules/esm/resolve.js:699:10)
0|npm      |     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
0|npm      |     at Loader.resolve (internal/modules/esm/loader.js:86:40)
0|npm      |     at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
0|npm      |     at Loader.import (internal/modules/esm/loader.js:165:28)
0|npm      |     at importModuleDynamically (internal/modules/cjs/loader.js:1006:27)
0|npm      |     at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
0|npm      |     at Object.<anonymous> (/home/dhruv/.nvm/versions/node/v14.16.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:30:16)
0|npm      |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
0|npm      |   code: 'ERR_UNSUPPORTED_DIR_IMPORT',
0|npm      |   url: 'file://Programs/npm'
0|npm      | }
```

**Comment by DurandSacha** [comment]
`pm2 start "node -- index.js" ` and `pm2 start index.js`

seems to cause less error

**Comment by ckcr4lyf** [comment]
> If it can help someone, I found the following workaround :
> 
> pm2 start "node -- /path/to/app.js"
> 
> For this configuration:
> 
> pm2: 4.1.2
> node: 14.16.1 (using n)
> package.json: has "type": "module"
> file extension: js
> os: centOS

This is what worked for me, since the `app.js` file was not in the root. many thanks!

**Comment by EskelCz** [comment]
What worked for me to make it run with ecosystem config was naming it ecosystem.config.cjs, and starting with `pm2 start ecosystem.config.cjs`

**Comment by bentaber** [comment]
I'll echo @EskelCz in that renaming your ecoystem file to end with `.cjs`, and of course using common js module syntax inside of that file for requires and exports, *seems* to be working

**Comment by CallumWalterWhite** [comment]
> If it can help someone, I found the following workaround :
> 
> pm2 start "node -- /path/to/app.js"
> 
> For this configuration:
> 
> pm2: 4.1.2 node: 14.16.1 (using n) package.json: has "type": "module" file extension: js os: centOS

This worked for me, thank you so much!

**Comment by muhammedkamel** [comment]
@Unitech Any updates with `node 14` I am using `pm2 v5` and still have the same problem

**Comment by mreinstein** [comment]
esm is natively supported, stable in all active LTS distributions. Is this not something pm2 ever plans to support?

**Comment by fvilar** [comment]
Working for me with a package.json inside the route. 
if you have ` modules/app.js`, just add a `modules/package.json`

`package.json `
```
{
  "version": "1.0.0",
  "type": "module"
}
```

**Comment by jays0606** [comment]
> npm install pm2@latest -g

love you fixed!

**Comment by jrs320** [comment]
> 

Has the problem been solved?

**Comment by jrs320** [comment]
> @Unitech Any updates with `node 14` I am using `pm2 v5` and still have the same problem.
> 
> I changed the config name to `ecosystem.config.cjs` then
> 
> ```shell
> pm2 start ecosystem.config.cjs
> ```

Has the problem been solved?

**Comment by DenProgMan** [comment]
Yes the problem is solved. This solution worked for me.

чт, 6 янв. 2022 г., 17:35 Ramsay Jiang ***@***.***>:

**Comment by jaclas** [comment]
I still get many errors, I use node 17.3, pm2  5.1.2 and ESM...

**Comment by Diferno** [comment]
Yup, same here.
After many years working with pm2 and commonjs, changing to ESM and bumping into this is really frustrating.

**Comment by roeniss** [comment]
I think [this comment](https://github.com/Unitech/pm2/issues/4540#issuecomment-841902463) should get a prize:

>  really simple "workaround" is to just write your config file in YAML

Thank you so much, @adamhl8 !

**Comment by bryce-mullican** [comment]
Like others I was frustrated with having issues with pm2. After reading:



 the comments by I am using "ecosystem.config.cjs". I was able to work around the problem by creating a "package.json" file 

os: Ubuntu
node: v16.3.0
pm2: 5.2.0

**Comment by Firsh** [comment]
Ok, so `"type": "module",` is given. In the [docs](https://pm2.keymetrics.io/docs/usage/application-declaration/) you need to read very closely to notice the mention of being able to use a json config file. And you need to go right to the [ecosystem config file examples](https://github.com/Unitech/pm2/tree/master/examples/ecosystem-file) to reveal that even yaml is supported.

This **ecosystem.config.js** doesn't work yet it's all you see in the docs:
```
module.exports = {
  apps: [{
    name: "app1",
    script: "./index.js"
  }]
}
```

But this **ecosystem.config.json** works:
```
{
  "apps": [{
    "name": "app1",
    "script": "./index.js"
  }]
}
```

Also this ecosystem.config.yaml works:

```
apps:
  - name : 'app1'
    script: './index.js'
```

If you really want to stick with a JS file to not change syntax much, this **ecosystem.config.es6.js** works as well:
```
export default {
  apps: [{
    name: "app1",
    script: "./index.js"
  }]
}
```
I'm not saying the docs are bad, but they certainly don't cover every _new_ kind of possibility.

**Comment by dzek69** [comment]
2 and a half year with no luck? That's a shame :(

Anyway, the simplest solution is the one from @nickpharrison

Near your index.js or whatever create `entry.mjs` file with `import "./index.js"` and run it instead. It just works, the .mjs extension is what forces node into ESM mode.

**Comment by FbN** [comment]
I was starting to think that pm2 is superfluous. You can better manage
integrating directly with systemd

Il ven 3 giu 2022, 21:33 Jacek Nowacki ***@***.***> ha
scritto:

**Comment by mreinstein** [comment]
>  was starting to think that pm2 is superfluous. You can better manage

100% agreed, pm2 (and other service wrappers) aren't needed in 2022.

**Comment by rhwinter** [comment]
Things get even weirder if one is trying to use `pm2 deploy`, so I'll add this comment for future reference.

Unlike what @Firsh mentions, the `json` variant of the `ecosystem` file can't be named ~~`ecosystem.config.json`~~, but **`ecosystem.json`**; if only a `ecosystem.config.json` file is present, it will be skipped and `packages.json` will be used.

Also, using an `ecosystem.config.es6.js` or an `ecosystem.config.cjs` file doesn't seem to work when issuing `pm2 deploy`. Indeed, checking [the deploy code](https://github.com/Unitech/pm2/blob/master/lib/API/Deploy.js#L70), one can find:
```javascript
var defaultConfigNames = ['ecosystem.config.js', 'ecosystem.json', 'ecosystem.json5', 'package.json'];
```
So, clearly, those are the only file names allowed.

Also, any of them will by parsed (by calling [Common.parseConfig()](https://github.com/Unitech/pm2/blob/master/lib/API/Deploy.js#L85)) and end up being [required](https://github.com/Unitech/pm2/blob/master/lib/Common.js#L317), which is, needless to say, very frustrating if your entire project is using ES6 modules — in other words, as far as I can tell, the only way to use `deploy` in that case is to have a `ecosystem.json` file or to explicitly declare the config file, like so:
```
$ pm2 deploy ecosystem.config.cjs production
```
where `production` is the environment set in the file itself.

It would be nice if pm2 caught that automatically, which, it now occurs to me, would just require adding `ecosystem.config.cjs` to [the deploy code](https://github.com/Unitech/pm2/blob/master/lib/API/Deploy.js#L70):
```diff
@@ -67,7 +67,7 @@ module.exports = function(CLI) {
     // Find ecosystem file by default
     if (!Common.isConfigFile(file)) {
       env = args[0];
-      var defaultConfigNames = ['ecosystem.config.js', 'ecosystem.json', 'ecosystem.json5', 'package.json'];
+      var defaultConfigNames = ['ecosystem.config.js', 'ecosystem.config.cjs', 'ecosystem.json', 'ecosystem.json5', 'package.json'];
       file = Utility.whichFileExists(defaultConfigNames);
 
       if (!file) {
```

**Comment by GimpMaster** [comment]
@rhwinter - Agreed, it would be nice if they added ecosystem.config.cjs. I had this exact same issue a week ago and like you said you have to manually specify ecosystem.config.cjs on the command line. It sure would be nice if they added cjs as well. Can you create a pull request?

**Comment by mmxhello** [comment]
Wow, I couldn't solve this for 2 weeks, but now it's done.
The problem was that node version on my server was 12, but the latest for now is 19. 
I checked it with:
`node --version`
Then installed a package to update node:
`sudo npm install -g n`
And, to update:
`sudo n latest`
Rebooted server
`sudo reboot`
And it works!

**Comment by PlebeiusGaragicus** [comment]
Searching for this issue brought me here.  Trying to run pm2 on a Debian 11 Linode instance - ran into issues.  I had installed node with `apt install` and it gave me v12.12.something.  Uninstalled that and used the snap store instead and I got version v18.15.0 - problem solved.  I am very much a beginner and was starting to lose hope.

**Comment by virtuallyunknown** [comment]
There is an example above illustrated by @Firsh that uses a `ecosystem.config.es6.js` file. Unfortunately this doesn't appear to be working as intended. If you issue the `pm2 start ecosystem.config.es6.js` command, it will treat it as a program rather than a configuration file, which is obviously not what you want.



```js
export default {
    apps: [
        {
            name: 'foo',
            script: 'node foo.js',
        },
        {
            name: 'bar',
            script: 'node bar.js',
        }
    ]
};

console.log("hello");
```

![image](https://github.com/Unitech/pm2/assets/24871108/7c9f095d-54bd-4b27-824a-ac984574cc85)

The `~/.pm2/logs/ecosystem.config.es6-out.log` file will just contain a bunch of `hello`s.

**Comment by GimpMaster** [comment]
It looks like in 5.3.1 this issue was solved for ecosystem.config.cjs

Here is the commit https://github.com/Unitech/pm2/commit/c810b9fa3b898c8dcfd5fa13b079e21a2afa77d6

If that is the case i think you can use `ecosystem.config.cjs` and type: module in your node project.

We could probably close this issue?

**Comment by jclaveau** [comment]
In my case `export default {...}` didn't work as the `default` entry return by `require` is not used: https://github.com/Unitech/pm2/blob/master/lib/Common.js#L331

To make it work I had to write 
```
export const apps = [
  // ...
]
```

**Comment by virtuallyunknown** [comment]
@jclaveau I'm sorry, I honestly don't remember anymore, haven't used pm2 in a while. All I see is I gave thumbs up to this reply, which probably means that ended up what I used:

https://github.com/Unitech/pm2/issues/4540#issuecomment-1937854146

**Comment by simwai** [comment]
> In my case `export default { apps: [...]}` didn't work as the `default` entry return by `require` is not used: https://github.com/Unitech/pm2/blob/master/lib/Common.js#L331
> 
> To make it work I had to write
> 
> ```
> export const apps = [
>   // ...
> ]
> ```
> 
> Is it your problem also [@virtuallyunknown](https://github.com/virtuallyunknown) ?

Thanks dude life saver!!!
