### ISSUE TITLE
Pino logging getting lost with pm2

### ISSUE THREAD

**Issue by gordonbazeley** [Unitech/pm2#4872]
## What's going wrong?
I'm using pino for logging but when using pm2 my logs are not showing up - this [issue on the pino github](https://github.com/pinojs/pino/issues/491) suggests it's down to pm2 doing something non standard with process.stdout.

For now I've switched to forever on production since that doesn't have this issue but would like to move back to pm2.

## How could we reproduce this issue?
Add pino to a script and log something - note that it doesn't show up in pm2 logs

## Supporting information
[Pino docs](https://getpino.io/#/)

--- PM2 report ----------------------------------------------------------------
Date                 : Thu Oct 08 2020 05:23:36 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.4.0
node version         : 14.13.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.4.0
node version         : 14.13.0
node path            : /usr/bin/pm2
argv                 : /usr/bin/node,/usr/bin/pm2,report
argv0                : node
user                 : root
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
cpus nb              : 1
freemem              : 75190272
totalmem             : 1029009408
home                 : /root
===============================================================================
--- PM2 list -----------------------------------------------
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/root/.pm2/pm2.log last 20 lines:
PM2        | 2020-10-05T10:52:39: PM2 log: [PM2] This PM2 is not UP TO DATE
PM2        | 2020-10-05T10:52:39: PM2 log: [PM2] Upgrade to version 4.5.0
PM2        | 2020-10-06T09:02:01: PM2 log: pm2 has been killed by signal, dumping process list before exit...
PM2        | 2020-10-06T09:02:01: PM2 log: Exited peacefully
PM2        | 2020-10-08T05:23:36: PM2 log: ===============================================================================
PM2        | 2020-10-08T05:23:36: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2020-10-08T05:23:36: PM2 log: Time                 : Thu Oct 08 2020 05:23:36 GMT+0000 (Coordinated Universal Time)
PM2        | 2020-10-08T05:23:36: PM2 log: PM2 version          : 4.4.0
PM2        | 2020-10-08T05:23:36: PM2 log: Node.js version      : 14.13.0
PM2        | 2020-10-08T05:23:36: PM2 log: Current arch         : x64
PM2        | 2020-10-08T05:23:36: PM2 log: PM2 home             : /root/.pm2
PM2        | 2020-10-08T05:23:36: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2020-10-08T05:23:36: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2020-10-08T05:23:36: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2020-10-08T05:23:36: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2020-10-08T05:23:36: PM2 log: Worker Interval      : 30000
PM2        | 2020-10-08T05:23:36: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2020-10-08T05:23:36: PM2 log: Concurrent actions   : 2
PM2        | 2020-10-08T05:23:36: PM2 log: SIGTERM timeout      : 1600
PM2        | 2020-10-08T05:23:36: PM2 log: ===============================================================================

**Comment by delimmy** [comment]
Any update with this? It's been over half a year

**Comment by favoyang** [comment]
As mentioned in https://github.com/pinojs/pino/issues/491, it's been solved by https://github.com/pinojs/pino/pull/493.

To fix the issue, remove the destination parameter when creating the pino instance.

```
const logger = pino({
  level: 'info'
}, pino.destination({...}));

=> 

const logger = pino({
  level: 'info'
});
```

**Comment by squareloop1** [comment]
This still is not fixed for async logging in pino because of pm2 hijacking stdout. Is there a possibility to work around this to be able to use pino in async mode? This would boost log performance by a significant amount.

**Comment by HsinHeng** [comment]
Could PM2 support an optional parameter to not hijack process.stdout.write?
It's not a good idea to change behavior of native node.js core.

**Comment by dhalbrook** [comment]
Where in the current pm2 codebase is the `process.stdout.write` hijack done?  I'm running into this as well and might have a go at trying to create a PR to fix it.  It seems that "silent=true" should, at the very least, cause PM2 never to hit that block.

**Comment by HsinHeng** [comment]
> Where in the current pm2 codebase is the `process.stdout.write` hijack done? I'm running into this as well and might have a go at trying to create a PR to fix it. It seems that "silent=true" should, at the very least, cause PM2 never to hit that block.

Hi @dhalbrook, it's discuss at https://github.com/pinojs/pino/issues/491#issuecomment-414075492.
Maybe codebase is here https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js?

**Comment by cage1618** [comment]
Same problem here

**Comment by bitliner** [comment]
same issue here, my temporary workaround is to add a transport with file target (to have your own log file, not pm2 log file)

```
import pino from 'pino';
import pinoPretty from 'pino-pretty';
const __dirname = import.meta.dirname;

const transport = pino.transport({
  targets: [
    {
      level: 'info',
      target: 'pino/file',
      options: { destination: `${__dirname}/file.log` },
    },
    {
      level: 'info',
      target: 'pino-pretty',
      colorize: true,
    },
  ],
});


export default pino(transport);

```
