### ISSUE TITLE
util.isArray is deprecated

### ISSUE THREAD

**Issue by andrepadez** [Unitech/pm2#5821]
## What's going wrong?
I'm getting the warning:
```
(node:50947) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
```

## How could we reproduce this issue?

any time i run `pm2 start` or `pm2 stop`,

## Supporting information
- pm2 version: 5.3.1
- nodejs version:  22.2.0

```
# Run the following commands
$ pm2 report
```

```
--- PM2 report ----------------------------------------------------------------
Date                 : Sat May 18 2024 09:07:33 GMT+0100 (Western European Summer Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 5.3.1
node version         : 22.2.0
node path            : /Users/andrepadez/.bun/bin/bun
argv                 : /opt/homebrew/Cellar/node/22.2.0/bin/node,/opt/homebrew/lib/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : andrepadez
uid                  : 501
gid                  : 20
uptime               : 2816min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 5.3.1
node version         : 22.2.0
node path            : /opt/homebrew/bin/pm2
argv                 : /opt/homebrew/Cellar/node/22.2.0/bin/node,/opt/homebrew/bin/pm2,report
argv0                : node
user                 : andrepadez
uid                  : 501
gid                  : 20
===============================================================================
--- System info --------------------------------------------
arch                 : arm64
platform             : darwin
type                 : Darwin
cpus                 : Apple M2 Pro
cpus nb              : 12
freemem              : 286654464
totalmem             : 17179869184
home                 : /Users/andrepadez
===============================================================================
--- PM2 list -----------------------------------------------
┌────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 6  │ AGGREGATOR SERVICE    │ default     │ N/A     │ fork    │ 14639    │ 15h    │ 1    │ online    │ 0%       │ 800.0kb  │ and… │ disabled │
│ 1  │ API SERVER            │ default     │ N/A     │ fork    │ 50966    │ 3m     │ 0    │ online    │ 0%       │ 2.0mb    │ and… │ disabled │
│ 0  │ AUTHENTICATION        │ default     │ N/A     │ fork    │ 14068    │ 15h    │ 3    │ online    │ 0%       │ 800.0kb  │ and… │ disabled │
│ 7  │ DASHBOARD             │ default     │ N/A     │ fork    │ 14904    │ 15h    │ 0    │ online    │ 0%       │ 800.0kb  │ and… │ disabled │
│ 9  │ DRIZZLE STUDIO        │ default     │ N/A     │ fork    │ 23758    │ 45h    │ 47   │ online    │ 0%       │ 320.0kb  │ and… │ disabled │
│ 8  │ EDITOR                │ default     │ N/A     │ fork    │ 0        │ 0      │ 0    │ stopped   │ 0%       │ 0b       │ and… │ disabled │
│ 2  │ EXPERIMENTS SERVER    │ default     │ N/A     │ fork    │ 20376    │ 46h    │ 0    │ online    │ 0%       │ 320.0kb  │ and… │ disabled │
│ 4  │ GAN SERVER            │ default     │ N/A     │ fork    │ 29356    │ 44h    │ 4    │ online    │ 0%       │ 320.0kb  │ and… │ disabled │
│ 5  │ NOTIFIER SERVER       │ default     │ N/A     │ fork    │ 20500    │ 46h    │ 0    │ online    │ 0%       │ 320.0kb  │ and… │ disabled │
│ 3  │ STATISTICS SERVER     │ default     │ N/A     │ fork    │ 20418    │ 46h    │ 0    │ online    │ 0%       │ 320.0kb  │ and… │ disabled │
└────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/andrepadez/.pm2/pm2.log last 20 lines:
PM2        | 2024-05-17T17:13:40: PM2 log: App [AUTHENTICATION:0] exited with code [1] via signal [SIGINT]
PM2        | 2024-05-17T17:13:40: PM2 log: App [AUTHENTICATION:0] starting in -fork mode-
PM2        | 2024-05-17T17:13:40: PM2 log: App [AUTHENTICATION:0] online
PM2        | 2024-05-17T17:16:40: PM2 log: Stopping app:AGGREGATOR SERVICE id:6
PM2        | 2024-05-17T17:16:40: PM2 log: App [AGGREGATOR SERVICE:6] exited with code [0] via signal [SIGINT]
PM2        | 2024-05-17T17:16:40: PM2 log: pid=20541 msg=process killed
PM2        | 2024-05-17T17:16:40: PM2 log: App [AGGREGATOR SERVICE:6] starting in -fork mode-
PM2        | 2024-05-17T17:16:40: PM2 log: App [AGGREGATOR SERVICE:6] online
PM2        | 2024-05-17T17:16:46: PM2 log: App [DASHBOARD:7] starting in -fork mode-
PM2        | 2024-05-17T17:16:46: PM2 log: App [DASHBOARD:7] online
PM2        | 2024-05-17T17:17:14: PM2 log: Stopping app:DASHBOARD id:7
PM2        | 2024-05-17T17:17:14: PM2 log: App [DASHBOARD:7] exited with code [0] via signal [SIGINT]
PM2        | 2024-05-17T17:17:14: PM2 log: pid=14705 msg=process killed
PM2        | 2024-05-17T17:17:46: PM2 log: App [DASHBOARD:7] starting in -fork mode-
PM2        | 2024-05-17T17:17:46: PM2 log: App [DASHBOARD:7] online
PM2        | 2024-05-17T18:33:46: PM2 log: Stopping app:API SERVER id:1
PM2        | 2024-05-17T18:33:46: PM2 log: App [API SERVER:1] exited with code [0] via signal [SIGINT]
PM2        | 2024-05-17T18:33:46: PM2 log: pid=92921 msg=process killed
PM2        | 2024-05-18T09:04:02: PM2 log: App [API SERVER:1] starting in -fork mode-
PM2        | 2024-05-18T09:04:02: PM2 log: App [API SERVER:1] online

```

**Comment by tayeb-khan** [comment]
@andrepadez do you get any solution of that issue brother, facing the same issues here.

**Comment by andrepadez** [comment]
> @andrepadez do you get any solution of that issue brother, facing the same issues here.

I fixed it myself in a pull request that has just been merged into 'develop'. Let's hope it gets released soon

https://github.com/Unitech/pm2/pull/5822

**Comment by WildanMZaki** [comment]
I think they have resolved this issue. I faced the same problem, and saw this repo updated a few hours ago. Then after I updated my pm2, my application returned to running normally. Thanks to everyone

**Comment by AdetonaMichael** [comment]
I am also getting this error. Please What is the way out?

**Comment by andrepadez** [comment]
Just update pm2. It has been fixed shortly after this issue was created

**Comment by Lordfirespeed** [comment]
I am still having this issue using the latest version of pm2, 5.4.2.

**Comment by rayhaans** [comment]
Mar 21 20:30:30 aauc3splxmqt002 Node-RED[42797]: (node:42797) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable >
Mar 21 20:30:31 aauc3splxmqt002 Node-RED[42797]: (node:42797) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP addre>

**Comment by smhk** [comment]
if it helps anyone the ONLY way I could fix this on a typical aws Ubuntu was

```
.. update node, npm, etc etc
] npm install pm2 -g
] npm install pm2
] pm2 update
] pm2 unstartup
```

AND  literally **restart the server**.  (You then have to pm2 update, etc etc.)

Hope it helps someone
