### ISSUE TITLE
Error pm2-runtine docker aws ecs

### ISSUE THREAD

**Issue by Chiliseo** [Unitech/pm2#5916]
## What's going wrong?
Error: Cannot find module '/usr/local/lib/binaries/Runtime4Docker.js'

also

node:internal/modules/cjs/loader:1143
throw err;
^
Error: Cannot find module '/usr/local/lib/binaries/CLI.js'
at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
at Module._load (node:internal/modules/cjs/loader:981:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
at node:internal/main/run_main_module:28:49 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Node.js v18.20.4

## Supporting information

```
# Run the following commands
$ pm2 report
```

**Comment by JennyLin77** [comment]
the problem I met was similar with you

![image](https://github.com/user-attachments/assets/f5c7e986-1f5f-4a2c-8628-8b3de0b622a5)
but when I rerun pipeline, and the problem was solved

**Comment by Miantang** [comment]
I fixed it when return back to v5.4.2

**Comment by vickyRathee** [comment]
I am still getting the error in latest version `6.0.8` while deploying on Elastic Beanstalk, so this docs is broken

https://pm2.keymetrics.io/docs/tutorials/use-pm2-with-aws-elastic-beanstalk/ 

```
Jul 29 08:30:13 ip-172-31-3-65 web[12904]: > pm2-runtime start pm2-app.json --env production
Jul 29 08:30:13 ip-172-31-3-65 web[12923]: node:internal/modules/cjs/loader:1404
Jul 29 08:30:13 ip-172-31-3-65 web[12923]:  throw err;
Jul 29 08:30:13 ip-172-31-3-65 web[12923]:  ^
Jul 29 08:30:13 ip-172-31-3-65 web[12923]: Error: Cannot find module '../lib/binaries/Runtime4Docker.js'
```
